/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as JoinTokenRouteImport } from './routes/join/$token'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedFootballPickEmIndexRouteImport } from './routes/_authenticated/football/pick-em/index'
import { Route as AuthenticatedFootballPickEmCreateRouteImport } from './routes/_authenticated/football/pick-em/create'
import { Route as AuthenticatedFootballPickEmLeagueIdRouteImport } from './routes/_authenticated/football/pick-em/$leagueId'
import { Route as AuthenticatedFootballPickEmLeagueIdIndexRouteImport } from './routes/_authenticated/football/pick-em/$leagueId.index'
import { Route as AuthenticatedFootballPickEmLeagueIdSettingsRouteImport } from './routes/_authenticated/football/pick-em/$leagueId.settings'
import { Route as AuthenticatedFootballPickEmLeagueIdMyPicksRouteImport } from './routes/_authenticated/football/pick-em/$leagueId.my-picks'
import { Route as AuthenticatedFootballPickEmLeagueIdMembersRouteImport } from './routes/_authenticated/football/pick-em/$leagueId.members'
import { Route as AuthenticatedFootballPickEmLeagueIdLeaguePicksRouteImport } from './routes/_authenticated/football/pick-em/$leagueId.league-picks'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFootballPickEmIndexRoute =
  AuthenticatedFootballPickEmIndexRouteImport.update({
    id: '/football/pick-em/',
    path: '/football/pick-em/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFootballPickEmCreateRoute =
  AuthenticatedFootballPickEmCreateRouteImport.update({
    id: '/football/pick-em/create',
    path: '/football/pick-em/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFootballPickEmLeagueIdRoute =
  AuthenticatedFootballPickEmLeagueIdRouteImport.update({
    id: '/football/pick-em/$leagueId',
    path: '/football/pick-em/$leagueId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFootballPickEmLeagueIdIndexRoute =
  AuthenticatedFootballPickEmLeagueIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFootballPickEmLeagueIdRoute,
  } as any)
const AuthenticatedFootballPickEmLeagueIdSettingsRoute =
  AuthenticatedFootballPickEmLeagueIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedFootballPickEmLeagueIdRoute,
  } as any)
const AuthenticatedFootballPickEmLeagueIdMyPicksRoute =
  AuthenticatedFootballPickEmLeagueIdMyPicksRouteImport.update({
    id: '/my-picks',
    path: '/my-picks',
    getParentRoute: () => AuthenticatedFootballPickEmLeagueIdRoute,
  } as any)
const AuthenticatedFootballPickEmLeagueIdMembersRoute =
  AuthenticatedFootballPickEmLeagueIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedFootballPickEmLeagueIdRoute,
  } as any)
const AuthenticatedFootballPickEmLeagueIdLeaguePicksRoute =
  AuthenticatedFootballPickEmLeagueIdLeaguePicksRouteImport.update({
    id: '/league-picks',
    path: '/league-picks',
    getParentRoute: () => AuthenticatedFootballPickEmLeagueIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/join/$token': typeof JoinTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/football/pick-em/$leagueId': typeof AuthenticatedFootballPickEmLeagueIdRouteWithChildren
  '/football/pick-em/create': typeof AuthenticatedFootballPickEmCreateRoute
  '/football/pick-em': typeof AuthenticatedFootballPickEmIndexRoute
  '/football/pick-em/$leagueId/league-picks': typeof AuthenticatedFootballPickEmLeagueIdLeaguePicksRoute
  '/football/pick-em/$leagueId/members': typeof AuthenticatedFootballPickEmLeagueIdMembersRoute
  '/football/pick-em/$leagueId/my-picks': typeof AuthenticatedFootballPickEmLeagueIdMyPicksRoute
  '/football/pick-em/$leagueId/settings': typeof AuthenticatedFootballPickEmLeagueIdSettingsRoute
  '/football/pick-em/$leagueId/': typeof AuthenticatedFootballPickEmLeagueIdIndexRoute
}
export interface FileRoutesByTo {
  '/join/$token': typeof JoinTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/football/pick-em/create': typeof AuthenticatedFootballPickEmCreateRoute
  '/football/pick-em': typeof AuthenticatedFootballPickEmIndexRoute
  '/football/pick-em/$leagueId/league-picks': typeof AuthenticatedFootballPickEmLeagueIdLeaguePicksRoute
  '/football/pick-em/$leagueId/members': typeof AuthenticatedFootballPickEmLeagueIdMembersRoute
  '/football/pick-em/$leagueId/my-picks': typeof AuthenticatedFootballPickEmLeagueIdMyPicksRoute
  '/football/pick-em/$leagueId/settings': typeof AuthenticatedFootballPickEmLeagueIdSettingsRoute
  '/football/pick-em/$leagueId': typeof AuthenticatedFootballPickEmLeagueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/football/pick-em/$leagueId': typeof AuthenticatedFootballPickEmLeagueIdRouteWithChildren
  '/_authenticated/football/pick-em/create': typeof AuthenticatedFootballPickEmCreateRoute
  '/_authenticated/football/pick-em/': typeof AuthenticatedFootballPickEmIndexRoute
  '/_authenticated/football/pick-em/$leagueId/league-picks': typeof AuthenticatedFootballPickEmLeagueIdLeaguePicksRoute
  '/_authenticated/football/pick-em/$leagueId/members': typeof AuthenticatedFootballPickEmLeagueIdMembersRoute
  '/_authenticated/football/pick-em/$leagueId/my-picks': typeof AuthenticatedFootballPickEmLeagueIdMyPicksRoute
  '/_authenticated/football/pick-em/$leagueId/settings': typeof AuthenticatedFootballPickEmLeagueIdSettingsRoute
  '/_authenticated/football/pick-em/$leagueId/': typeof AuthenticatedFootballPickEmLeagueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/join/$token'
    | '/'
    | '/login'
    | '/profile'
    | '/football/pick-em/$leagueId'
    | '/football/pick-em/create'
    | '/football/pick-em'
    | '/football/pick-em/$leagueId/league-picks'
    | '/football/pick-em/$leagueId/members'
    | '/football/pick-em/$leagueId/my-picks'
    | '/football/pick-em/$leagueId/settings'
    | '/football/pick-em/$leagueId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/join/$token'
    | '/'
    | '/login'
    | '/profile'
    | '/football/pick-em/create'
    | '/football/pick-em'
    | '/football/pick-em/$leagueId/league-picks'
    | '/football/pick-em/$leagueId/members'
    | '/football/pick-em/$leagueId/my-picks'
    | '/football/pick-em/$leagueId/settings'
    | '/football/pick-em/$leagueId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/join/$token'
    | '/_authenticated/'
    | '/login/'
    | '/_authenticated/profile/'
    | '/_authenticated/football/pick-em/$leagueId'
    | '/_authenticated/football/pick-em/create'
    | '/_authenticated/football/pick-em/'
    | '/_authenticated/football/pick-em/$leagueId/league-picks'
    | '/_authenticated/football/pick-em/$leagueId/members'
    | '/_authenticated/football/pick-em/$leagueId/my-picks'
    | '/_authenticated/football/pick-em/$leagueId/settings'
    | '/_authenticated/football/pick-em/$leagueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  JoinTokenRoute: typeof JoinTokenRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/football/pick-em/': {
      id: '/_authenticated/football/pick-em/'
      path: '/football/pick-em'
      fullPath: '/football/pick-em'
      preLoaderRoute: typeof AuthenticatedFootballPickEmIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/football/pick-em/create': {
      id: '/_authenticated/football/pick-em/create'
      path: '/football/pick-em/create'
      fullPath: '/football/pick-em/create'
      preLoaderRoute: typeof AuthenticatedFootballPickEmCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/football/pick-em/$leagueId': {
      id: '/_authenticated/football/pick-em/$leagueId'
      path: '/football/pick-em/$leagueId'
      fullPath: '/football/pick-em/$leagueId'
      preLoaderRoute: typeof AuthenticatedFootballPickEmLeagueIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/football/pick-em/$leagueId/': {
      id: '/_authenticated/football/pick-em/$leagueId/'
      path: '/'
      fullPath: '/football/pick-em/$leagueId/'
      preLoaderRoute: typeof AuthenticatedFootballPickEmLeagueIdIndexRouteImport
      parentRoute: typeof AuthenticatedFootballPickEmLeagueIdRoute
    }
    '/_authenticated/football/pick-em/$leagueId/settings': {
      id: '/_authenticated/football/pick-em/$leagueId/settings'
      path: '/settings'
      fullPath: '/football/pick-em/$leagueId/settings'
      preLoaderRoute: typeof AuthenticatedFootballPickEmLeagueIdSettingsRouteImport
      parentRoute: typeof AuthenticatedFootballPickEmLeagueIdRoute
    }
    '/_authenticated/football/pick-em/$leagueId/my-picks': {
      id: '/_authenticated/football/pick-em/$leagueId/my-picks'
      path: '/my-picks'
      fullPath: '/football/pick-em/$leagueId/my-picks'
      preLoaderRoute: typeof AuthenticatedFootballPickEmLeagueIdMyPicksRouteImport
      parentRoute: typeof AuthenticatedFootballPickEmLeagueIdRoute
    }
    '/_authenticated/football/pick-em/$leagueId/members': {
      id: '/_authenticated/football/pick-em/$leagueId/members'
      path: '/members'
      fullPath: '/football/pick-em/$leagueId/members'
      preLoaderRoute: typeof AuthenticatedFootballPickEmLeagueIdMembersRouteImport
      parentRoute: typeof AuthenticatedFootballPickEmLeagueIdRoute
    }
    '/_authenticated/football/pick-em/$leagueId/league-picks': {
      id: '/_authenticated/football/pick-em/$leagueId/league-picks'
      path: '/league-picks'
      fullPath: '/football/pick-em/$leagueId/league-picks'
      preLoaderRoute: typeof AuthenticatedFootballPickEmLeagueIdLeaguePicksRouteImport
      parentRoute: typeof AuthenticatedFootballPickEmLeagueIdRoute
    }
  }
}

interface AuthenticatedFootballPickEmLeagueIdRouteChildren {
  AuthenticatedFootballPickEmLeagueIdLeaguePicksRoute: typeof AuthenticatedFootballPickEmLeagueIdLeaguePicksRoute
  AuthenticatedFootballPickEmLeagueIdMembersRoute: typeof AuthenticatedFootballPickEmLeagueIdMembersRoute
  AuthenticatedFootballPickEmLeagueIdMyPicksRoute: typeof AuthenticatedFootballPickEmLeagueIdMyPicksRoute
  AuthenticatedFootballPickEmLeagueIdSettingsRoute: typeof AuthenticatedFootballPickEmLeagueIdSettingsRoute
  AuthenticatedFootballPickEmLeagueIdIndexRoute: typeof AuthenticatedFootballPickEmLeagueIdIndexRoute
}

const AuthenticatedFootballPickEmLeagueIdRouteChildren: AuthenticatedFootballPickEmLeagueIdRouteChildren =
  {
    AuthenticatedFootballPickEmLeagueIdLeaguePicksRoute:
      AuthenticatedFootballPickEmLeagueIdLeaguePicksRoute,
    AuthenticatedFootballPickEmLeagueIdMembersRoute:
      AuthenticatedFootballPickEmLeagueIdMembersRoute,
    AuthenticatedFootballPickEmLeagueIdMyPicksRoute:
      AuthenticatedFootballPickEmLeagueIdMyPicksRoute,
    AuthenticatedFootballPickEmLeagueIdSettingsRoute:
      AuthenticatedFootballPickEmLeagueIdSettingsRoute,
    AuthenticatedFootballPickEmLeagueIdIndexRoute:
      AuthenticatedFootballPickEmLeagueIdIndexRoute,
  }

const AuthenticatedFootballPickEmLeagueIdRouteWithChildren =
  AuthenticatedFootballPickEmLeagueIdRoute._addFileChildren(
    AuthenticatedFootballPickEmLeagueIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedFootballPickEmLeagueIdRoute: typeof AuthenticatedFootballPickEmLeagueIdRouteWithChildren
  AuthenticatedFootballPickEmCreateRoute: typeof AuthenticatedFootballPickEmCreateRoute
  AuthenticatedFootballPickEmIndexRoute: typeof AuthenticatedFootballPickEmIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedFootballPickEmLeagueIdRoute:
    AuthenticatedFootballPickEmLeagueIdRouteWithChildren,
  AuthenticatedFootballPickEmCreateRoute:
    AuthenticatedFootballPickEmCreateRoute,
  AuthenticatedFootballPickEmIndexRoute: AuthenticatedFootballPickEmIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  JoinTokenRoute: JoinTokenRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
